@startuml diagramafnaf2

class Guardia {
  - Camara camara[]
  - Mascara mascara
  - MusicBox musicBox
  - Linterna linterna
  - Luz luz[]
}

class Personaje

class Animatronico {
  - Pasillo pasillo
  - Ventilacion ventilacion
  - JumpScare jumpScare
}

class AnimatronicoOriginal
class AnimatronicoToy
class Freddy
class ToyFreddy
class Bonnie
class ToyBonnie
class Chica
class ToyChica
class Foxy
class Mangle
class GoldenFreddy

class BalloonBoy {
  - Linterna linterna
}

class Marionette {
  - MusicBox musicBox
  - PrizeCorner prizeCorner
}

class Oficina {
  - Camara camara[]
  - Ventilacion ventilacion
  - Linterna linterna
  - Luz luz[]
  - Mascara mascara
  - MusicBox musicBox
}

class Camara {
  + Monitorear(Guardia)
}
class Ventilacion {
  + Mover(Animatronico)
}
class Linterna {
  + Alumbrar(Guardia)
}
class Luz {
  + Encender(Guardia)
}
class Mascara {
  + Poner(Guardia)
}

class MusicBox {
  + Activar(Marionette)
  + Escuchar(Guardia)
}

class Noche {
  - Guardia guardia
  - Bateria bateria
  - JumpScare jumpScare[]
  - Turno turno
  - Escenario escenario
}

class JumpScare {
  + Asustar(Animatronico)
  + Ejecutar(Noche)
}

class Escenario {
  - Animatronico animatronico[]
}

class Pasillo {
  - Luz luz[]
  + Mover(Animatronico)
}

class Bateria

class PrizeCorner {
  - MusicBox musicBox
}

class Turno {
  + Iniciar()
  + Terminar()
}

Guardia              --|> Personaje
Animatronico         --|> Personaje
AnimatronicoOriginal --|> Animatronico
AnimatronicoToy      --|> Animatronico
Freddy               --|> AnimatronicoOriginal
Bonnie               --|> AnimatronicoOriginal
Chica                --|> AnimatronicoOriginal
Foxy                 --|> AnimatronicoOriginal
GoldenFreddy         --|> AnimatronicoOriginal
ToyFreddy            --|> AnimatronicoToy
ToyBonnie            --|> AnimatronicoToy
ToyChica             --|> AnimatronicoToy
Mangle               --|> AnimatronicoToy
BalloonBoy           --|> AnimatronicoToy
Marionette           --|> AnimatronicoToy

Oficina      "1" *-- "1..*" Camara
Oficina      "1" *-- "1"   Ventilacion
Oficina      "1" *-- "1"   Linterna
Oficina      "1" *-- "1..*" Luz
Oficina      "1" *-- "1"   Mascara
Oficina      "1" *-- "1"   MusicBox
Noche        "1" *-- "1"   Guardia
Noche        "1" *-- "1"   Bateria
Noche        "1" *-- "1"   Turno
Noche        "1" *-- "1"   Escenario
Escenario    "1" *-- "1..*" Animatronico
Pasillo      "1" *-- "1..*" Luz
PrizeCorner  "1" *-- "1"   MusicBox

Guardia      "1" o-- "1..*" Camara
Guardia      "1" o-- "1"   Mascara
Guardia      "1" o-- "1"   MusicBox
Guardia      "1" o-- "1..*" Luz
Guardia      "1" o-- "1"   Linterna
Animatronico "1" o-- "0..1" Pasillo
Animatronico "1" o-- "0..1" Ventilacion
Animatronico "1" o-- "0..1" JumpScare
Marionette   "1" o-- "1"   MusicBox
Marionette   "1" o-- "1"   PrizeCorner
BalloonBoy   "1" o-- "1"   Linterna
Noche        "1" o-- "0..*" JumpScare

@enduml