@startuml diagrama

class Guardia {
  - Camara camara[]
  - Mascara mascara
  - MusicBox musicBox
  - Luz luz[]
  - Energia energia
}

class Personaje

class Animatronico {
  - Pasillo pasillo
  - Ventilacion ventilacion
  - JumpScare jumpScare
}

class AnimatronicoOriginal
class AnimatronicoToy
class Freddy
class ToyFreddy
class Bonnie
class ToyBonnie
class Chica
class ToyChica
class Foxy
class Mangle
class GoldenFreddy

class BalloonBoy {
  - Energia energia
}

class Marionette {
  - CajaMusical cajaMusical
}

class Oficina {
  - Camara camara[]
  - Ventilacion ventilacion
  - Puerta puerta
  - Luz luz[]
  - Energia energia
  - Mascara mascara
  - MusicBox musicBox
}

class Camara {
  + Monitorear(Guardia)
}
class Ventilacion {
  + Mover(Animatronico)
}
class Puerta
class Luz {
  + Encender(Guardia)
}

class Energia {
  + Consumir(BalloonBoy)
  + Verificar(Guardia)
}

class Mascara {
  + Poner(Guardia)
}

class CajaMusical {
  - MusicBox musicBox
  + Activar(Marionette)
  + Escuchar(Guardia)
}

class MusicBox

class Noche {
  - Guardia guardia
  - Energia energia
  - Bateria bateria
  - JumpScare jumpScare[]
}

class JumpScare {
  + Asustar(Animatrónico)
  + Ejecutar(Noche)
}

class Escenario {
  - Animatronico animatronico[]
}

class Pasillo {
  - Luz luz[]
  + Mover(Animatrónico)
}

class Bateria

Guardia            --|> Personaje
Animatronico         --|> Personaje
AnimatronicoOriginal --|> Animatronico
AnimatronicoToy  --|> Animatronico
Freddy             --|> AnimatronicoOriginal
Bonnie             --|> AnimatronicoOriginal
Chica              --|> AnimatronicoOriginal
Foxy               --|> AnimatronicoOriginal
GoldenFreddy       --|> AnimatronicoOriginal
ToyFreddy          --|> AnimatronicoToy
ToyBonnie          --|> AnimatronicoToy
ToyChica           --|> AnimatronicoToy
Mangle             --|> AnimatronicoToy
BalloonBoy         --|> AnimatronicoToy
Marionette         --|> AnimatronicoToy

Oficina      "1" *-- "1..*" Camara
Oficina      "1" *-- "1" Ventilacion
Oficina      "1" *-- "1" Puerta
Oficina      "1" *-- "1..*" Luz
Oficina      "1" *-- "1" Energia
Oficina      "1" *-- "1" Mascara
Oficina      "1" *-- "1" MusicBox
Noche        "1" *-- "1" Guardia
Noche        "1" *-- "1" Energia
Noche        "1" *-- "1" Bateria
Escenario    "1" *-- "1..*" Animatronico
Pasillo      "1" *-- "1..*" Luz
CajaMusical  "1" *-- "1" MusicBox

Guardia      "1" o-- "1..*" Camara
Guardia      "1" o-- "1" Mascara
Guardia      "1" o-- "1" MusicBox
Guardia      "1" o-- "1..*" Luz
Guardia      "1" o-- "1" Energia
Animatronico "1..*" o-- "0..1" Pasillo
Animatronico "1..*" o-- "0..1" Ventilacion
Animatronico "1" o-- "0..1" JumpScare
Marionette   "1" o-- "1" CajaMusical
BalloonBoy   "1" o-- "1" Energia
Noche        "1" o-- "0..*" JumpScare

@enduml