@startuml diagrama

class Usuario
class Guardia{
  + Camara : Ver(Camara)
  + Mascara : Usar(Mascara)
  + MusicBox : Girar(MusicBox)
  + Luz : Activar(Luz)
  + Energia : Ver(Energia)
}

class Personaje
class Animatronico
class AnimatronicoOriginal
class AnimatronicoToy
class Freddy
class ToyFreddy
class Bonnie
class ToyBonnie
class Chica
class ToyChica
class Foxy
class Mangle
class GoldenFreddy
class BalloonBoy

class Marionette{
  + Jumpscare : Controlar(CajaMusical)
}

class Oficina{
  - Camara camara
  - Ventilacion ventilacion[2]
  - Puerta puerta
  - Luz luz[3]
  - Energia energia
  - Mascara mascara
  - MusicBox musicBox
}

class Camara
class Ventilacion
class Puerta
class Luz
class Energia
class Mascara
class CajaMusical
class MusicBox
class Noche
class JumpScare
class Escenario
class Pasillo
class Bateria

Guardia            --|> Personaje

Animatronico         --|> Personaje
AnimatronicoOriginal --|> Animatronico
AnimatronicoToy  --|> Animatronico

Freddy             --|> AnimatronicoOriginal
Bonnie             --|> AnimatronicoOriginal
Chica              --|> AnimatronicoOriginal
Foxy               --|> AnimatronicoOriginal
GoldenFreddy       --|> AnimatronicoOriginal

ToyFreddy          --|> AnimatronicoToy
ToyBonnie          --|> AnimatronicoToy
ToyChica           --|> AnimatronicoToy
Mangle             --|> AnimatronicoToy
BalloonBoy         --|> AnimatronicoToy
Marionette         --|> AnimatronicoToy

Oficina      "1" *-- "1..*" Camara
Oficina      "1" *-- "1" Ventilacion
Oficina      "1" *-- "1" Puerta
Oficina      "1" *-- "1..*" Luz
Oficina      "1" *-- "1" Energia
Oficina      "1" *-- "1" Mascara
Oficina      "1" *-- "1" MusicBox
Noche        "1" *-- "1" Guardia
Noche        "1" *-- "1" Energia
Noche        "1" *-- "1" Bateria
Escenario    "1" *-- "1..*" Animatronico
Pasillo      "1" *-- "1..*" Luz
CajaMusical  "1" *-- "1" MusicBox

Guardia      "1" o-- "1..*" Camara
Guardia      "1" o-- "1" Mascara
Guardia      "1" o-- "1" MusicBox
Guardia      "1" o-- "1..*" Luz
Guardia      "1" o-- "1" Energia
Animatronico "1..*" o-- "0..1" Pasillo
Animatronico "1..*" o-- "0..1" Ventilacion
Animatronico "1" o-- "0..1" JumpScare
Marionette   "1" o-- "1" CajaMusical
BalloonBoy   "1" o-- "1" Energia
Noche        "1" o-- "0..*" JumpScare

@enduml